### ISSUE TITLE
> Vale a pena atualizar o arquivo para mencionar o programa de recompensas de bugs.

### ISSUE THREAD

**Issue by Johnyratobravo** [ethereum-optimism/.github#11]
> Vale a pena atualizar o arquivo para mencionar o programa de recompensas de bugs.

Johnyratobravo

_Originally posted by @Johnyratobravo in https://github.com/ethereum-optimism/.github/issues/5#issuecomment-1548454680_

**Comment by philliprossii7** [comment]
#5
